version: '3'

services:
  identityDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - identityDB:/var/lib/mysql
    networks:
      - identityNet
      
  identityInit:
    image: identityinit
    environment:
      - DATABASE_URL=identityDB
    networks:
      - identityNet

  identity:
    image: identity
    environment:
      - DATABASE_URL=identityDB
    ports:
      - 5000:5000
    networks:
      - identityNet

  storeDB:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - storeDB:/var/lib/mysql
    networks:
      - storeNet
      
  storeInit:
    image: storeinit
    environment:
      - DATABASE_URL=storeDB
    networks:
      - storeNet

  owner:
    image: owner
    environment:
      - DATABASE_URL=storeDB
      - PRODUCTION=True
      - SOCKET_IP=0.0.0.0
      - SOCKET_PORT=9090
      - SPARKAPP_IP=sparkapp
    ports:
      - 5001:5000
    networks:
      - storeNet

  customer:
    image: customer
    environment:
      - DATABASE_URL=storeDB
    ports:
      - 5002:5000
    networks:
      - storeNet

  courier:
    image: courier
    environment:
      - DATABASE_URL=storeDB
    ports:
      - 5003:5000
    networks:
      - storeNet

  spark-master:
    image: bde2020/spark-master:3.3.0-hadoop3.3
    container_name: spark-master
    environment:
      - INIT_DAEMON_STEP=setup_spark

  spark-worker-1:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077

  spark-worker-2:
    image: bde2020/spark-worker:3.3.0-hadoop3.3
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      - SPARK_MASTER=spark://spark-master:7077

volumes:
  identityDB:
  storeDB:

networks:
  identityNet:
  storeNet: